Feature: navigation components
uug-ai/ui pull request #11
Opened 2024-05-24 14:39 UTC by LuisMaja

Within this feature request we will add a dynamic component for the icons and a item component for the navigation layout #8 #10

2024-05-27 15:10 UTC, cedricve requested changes
Not sure if this is the latest version, but requires more changes, see comments

2024-05-27 15:10 UTC, cedricve commented on src/components/DynamicIcon/index.tsx
> +  const IconComponent = React.lazy(() => import(`../icons/${type}`));
Is the issue resolved with the "not found" error?

<img width="1120" alt="Screenshot 2024-05-27 at 17 08 41" src="https://github.com/uug-ai/ui/assets/1546779/6d20c945-df09-48c9-9b33-cdbc758d80c9">

2024-05-27 15:10 UTC, cedricve commented on src/components/DynamicIcon/index.stories.tsx
> +export const Default: Story = {
@LuisMaja  currently there is only 1 icon. Could we visualise all of them with separate stories?

2024-05-27 15:10 UTC, cedricve commented on src/layouts/Navigation/index.tsx
> +    <Box className="border max-h-screen m-0 p-0">
Do we have a separate navigation item now?

2024-05-28 12:49 UTC, LuisMaja commented on src/components/DynamicIcon/index.tsx
> +  const IconComponent = React.lazy(() => import(`../icons/${type}`));
This has been fixed!

2024-05-30 09:38 UTC, LuisMaja commented on src/layouts/Navigation/index.tsx
> +    <Box className="border max-h-screen m-0 p-0">
The navigation item has been made and implemented into layout

2024-05-30 10:44 UTC, LuisMaja commented on src/components/DynamicIcon/index.stories.tsx
> +export const Default: Story = {
a story has been created to visualise all icons individually

2024-05-30 10:48 UTC, cedricve commented on src/components/DynamicIcon/index.stories.tsx
> +export const Default: Story = {
Looking good!! <3

2024-05-30 14:27 UTC, cedricve commented
a separate PR will be created

2024-05-30 14:27 UTC, closed without merging