Feature navigation
uug-ai/ui pull request #15
Opened 2024-05-30 14:35 UTC by LuisMaja

I've created the navigation Item and also a dynamic icon component both have been implemented into the navigation layout.

2024-05-30 14:36 UTC, LuisMaja commented
Please @KilianBoute and @cedricve, could you review this?

2024-05-31 08:38 UTC, KilianBoute approved these changes
Looks good

2024-05-31 08:44 UTC, cedricve requested changes
Luuking guut homie. Just replace the Loading text.

2024-05-31 08:44 UTC, cedricve commented on src/components/DynamicIcon/index.tsx
> +    <Suspense fallback={<div className="loading">Loading...</div>}>
We should print empty text instead of "Loading". It breaks the page layout. Or a static with.

2024-05-31 11:34 UTC, LuisMaja commented on src/components/DynamicIcon/index.tsx
> +    <Suspense fallback={<div className="loading">Loading...</div>}>
The lazyloading has been removed,  this will now make sure the page doesn't brake whenever visited/refreshed and increase UX.

2024-05-31 11:40 UTC, merged